from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import airfoil_codec
import util


DEFAULT_JSON_PATH = REPO_ROOT / "outputs" / "conventional_openvsp_obb" / "conventional_geometry.json"
NON_GUI_BACKENDS = {"agg", "pdf", "ps", "svg", "template"}
ELLIPSE_SAMPLES = 25
GEOMETRY_SCHEMA = "conventional_geometry_v1"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fit the source airfoil and show the conventional aircraft OBB drawing."
    )
    parser.add_argument(
        "--json",
        type=Path,
        default=DEFAULT_JSON_PATH,
        help="Path to conventional_geometry.json generated by create_obb_vsp.py.",
    )
    parser.add_argument(
        "--device",
        default="cpu",
        help="PyTorch device used for the Bezier fit, for example cpu or cuda.",
    )
    parser.add_argument(
        "--backend",
        default=None,
        help="Optional interactive matplotlib backend, for example TkAgg or QtAgg.",
    )
    return parser.parse_args()


def load_draw_payload(json_path: Path, device: str) -> tuple[list[list[float]], list[str]]:
    if not json_path.is_file():
        raise FileNotFoundError(f"Geometry JSON file does not exist: {json_path}")

    payload = json.loads(json_path.read_text(encoding="utf-8"))
    if payload.get("schema") != GEOMETRY_SCHEMA:
        raise ValueError(
            f"Geometry JSON schema must be {GEOMETRY_SCHEMA!r}, got {payload.get('schema')!r}"
        )
    for key in ("airfoil_source", "full_draw_components", "full_draw_box_order"):
        if key not in payload:
            raise KeyError(f"Geometry JSON missing required key: {key}")

    components = payload["full_draw_components"]
    labels = payload["full_draw_box_order"]
    validate_components(components, labels)
    fit_result = airfoil_codec.encode_processed_airfoil_dat(
        payload["airfoil_source"],
        device=device,
    )
    airfoil_code = fit_result["code"].tolist()
    boxes = [build_typed_obb_box(component, airfoil_code) for component in components]
    validate_typed_draw_boxes(boxes, labels)
    return boxes, labels


def validate_components(components: list[dict], labels: list[str]) -> None:
    if len(components) != len(labels):
        raise ValueError(
            f"full_draw_components length {len(components)} does not match label length {len(labels)}"
        )

    for index, (component_payload, label) in enumerate(zip(components, labels, strict=True)):
        for key in ("name", util.BOX_COMPONENT_KEY, util.BOX_GEOMETRY_KEY):
            if key not in component_payload:
                raise KeyError(f"full_draw_components[{index}] missing required key: {key}")
        if component_payload["name"] != label:
            raise ValueError(
                f"full_draw_components[{index}].name {component_payload['name']!r} does not match {label!r}"
            )
        component = component_payload[util.BOX_COMPONENT_KEY]
        if component not in util.COMPONENT_GEOMETRY_SIZES:
            raise ValueError(f"full_draw_components[{index}] has unknown component: {component}")
        geometry = component_payload[util.BOX_GEOMETRY_KEY]
        expected_size = util.COMPONENT_GEOMETRY_SIZES[component]
        if len(geometry) != expected_size:
            raise ValueError(
                f"full_draw_components[{index}] geometry has {len(geometry)} values, expected {expected_size}"
            )


def build_typed_obb_box(component_payload: dict, airfoil_code: list[float]) -> list[float]:
    component = component_payload[util.BOX_COMPONENT_KEY]
    box = [*component_payload[util.BOX_GEOMETRY_KEY]]
    if component == util.COMPONENT_WING:
        if len(airfoil_code) != util.AIRFOIL_BEZIER_CODE_SIZE:
            raise ValueError(
                f"Airfoil code has {len(airfoil_code)} values, expected {util.AIRFOIL_BEZIER_CODE_SIZE}"
            )
        box.extend(airfoil_code)
    box.extend(util.component_one_hot(component))

    expected_size = (
        util.WING_OBB_BOX_SIZE
        if component == util.COMPONENT_WING
        else util.STANDARD_OBB_BOX_SIZE
    )
    if len(box) != expected_size:
        raise ValueError(f"Typed OBB box has {len(box)} values, expected {expected_size}")
    return box


def validate_typed_draw_boxes(boxes: list[list[float]], labels: list[str]) -> None:
    if len(boxes) != len(labels):
        raise ValueError(
            f"full_draw_boxes length {len(boxes)} does not match full_draw_box_order length {len(labels)}"
        )
    for index, box in enumerate(boxes):
        component = component_from_box(box, f"full_draw_boxes[{index}]")
        expected_size = (
            util.WING_OBB_BOX_SIZE
            if component == util.COMPONENT_WING
            else util.STANDARD_OBB_BOX_SIZE
        )
        if len(box) != expected_size:
            raise ValueError(
                f"full_draw_boxes[{index}] has {len(box)} values, expected {expected_size}"
            )


def assert_interactive_backend(matplotlib) -> None:
    backend = matplotlib.get_backend()
    backend_key = backend.lower()
    if backend_key in NON_GUI_BACKENDS or "backend_inline" in backend_key:
        raise RuntimeError(f"Matplotlib backend {backend!r} cannot show an interactive OBB window")


def set_aircraft_axes(ax, boxes: list[list[float]]) -> None:
    import numpy as np

    xyz = []
    for box in boxes:
        xyz.append(box[0:3])
        xyz.append(box[3:6])

    xyz_array = np.asarray(xyz, dtype=float)
    center = xyz_array.mean(axis=0)
    max_range = max((xyz_array.max(axis=0) - xyz_array.min(axis=0)).max(), 1.0)
    radius = max_range * 0.62

    ax.set_xlim(center[0] - radius, center[0] + radius)
    ax.set_ylim(center[1] - radius, center[1] + radius)
    ax.set_zlim(center[2] - radius * 0.45, center[2] + radius * 0.75)
    ax.set_box_aspect((1.0, 1.0, 0.6))


def component_from_box(box: list[float], box_name: str) -> int:
    import numpy as np

    if len(box) < util.COMPONENT_CLASS_SIZE:
        raise ValueError(f"{box_name} lacks a component one-hot vector")
    component = int(np.argmax(box[-util.COMPONENT_CLASS_SIZE:]))
    if component not in util.COMPONENT_NAMES:
        raise ValueError(f"{box_name} has unknown component id: {component}")
    return component


def is_fuselage(box: list[float]) -> bool:
    return component_from_box(box, "OBB box") == util.COMPONENT_FUSELAGE


def is_wing(box: list[float]) -> bool:
    return component_from_box(box, "OBB box") == util.COMPONENT_WING


def is_engine(box: list[float]) -> bool:
    return component_from_box(box, "OBB box") == util.COMPONENT_ENGINE


def draw_elliptical_body(ax, box: list[float], label: str) -> None:
    import numpy as np

    start = np.asarray(box[0:3], dtype=float)
    end = np.asarray(box[3:6], dtype=float)
    axis = end - start
    axis_length = np.linalg.norm(axis)
    if axis_length == 0:
        raise ValueError(f"Elliptical-body OBB {label!r} has coincident endpoint centers")
    axis /= axis_length

    reference = np.array([0.0, 0.0, 1.0])
    if abs(np.dot(axis, reference)) > 0.95:
        reference = np.array([0.0, 1.0, 0.0])
    lateral = np.cross(axis, reference)
    lateral /= np.linalg.norm(lateral)
    vertical = np.cross(lateral, axis)

    theta = np.linspace(0.0, 2.0 * np.pi, ELLIPSE_SAMPLES)
    rings = []
    for center, width, height in (
        (start, box[6], box[7]),
        (end, box[8], box[9]),
    ):
        ring = (
            center[:, None]
            + lateral[:, None] * (width / 2.0) * np.cos(theta)
            + vertical[:, None] * (height / 2.0) * np.sin(theta)
        )
        rings.append(ring)
        ax.plot(ring[0], ring[1], ring[2], color="gray", linewidth=1.2)

    for sample in range(ELLIPSE_SAMPLES):
        ax.plot(
            [rings[0][0, sample], rings[1][0, sample]],
            [rings[0][1, sample], rings[1][1, sample]],
            [rings[0][2, sample], rings[1][2, sample]],
            color="gray",
            linewidth=0.8,
        )

    center = (start + end) / 2.0
    ax.text(center[0], center[1], center[2], label, color="black", fontsize=10)


def draw_wing_planform(ax, box: list[float], color, label: str) -> None:
    import numpy as np

    root = np.asarray(box[0:3], dtype=float)
    tip = np.asarray(box[3:6], dtype=float)
    root_chord = box[6]
    tip_chord = box[7]
    chord_axis = np.array([1.0, 0.0, 0.0])

    root_le = root - chord_axis * root_chord / 2.0
    root_te = root + chord_axis * root_chord / 2.0
    tip_le = tip - chord_axis * tip_chord / 2.0
    tip_te = tip + chord_axis * tip_chord / 2.0
    corners = (root_le, root_te, tip_te, tip_le, root_le)
    ax.plot(
        [corner[0] for corner in corners],
        [corner[1] for corner in corners],
        [corner[2] for corner in corners],
        color=color,
        linewidth=1.6,
    )

    center = (root + tip) / 2.0
    ax.text(center[0], center[1], center[2], label, color="black", fontsize=10)


def show_obb_aircraft(boxes: list[list[float]], labels: list[str]) -> None:
    import draw3dobb
    import matplotlib
    import matplotlib.pyplot as plt

    assert_interactive_backend(matplotlib)

    fig = plt.figure(figsize=(9, 6))
    ax = fig.add_subplot(111, projection="3d")
    cmap = plt.get_cmap("jet_r")

    for index, box in enumerate(boxes):
        if is_fuselage(box) or is_engine(box):
            draw_elliptical_body(ax, box, labels[index])
        elif is_wing(box):
            draw_wing_planform(ax, box, cmap(float(index) / len(boxes)), labels[index])
        else:
            draw3dobb.draw(ax, box, cmap(float(index) / len(boxes)), label=labels[index])

    set_aircraft_axes(ax, boxes)
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    ax.set_title("Conventional Aircraft OBB Encoding")
    ax.view_init(elev=22, azim=-58)

    print("Matplotlib backend:", matplotlib.get_backend(), flush=True)
    print("Showing OBB 3D window. Close the window to continue.", flush=True)
    plt.show()


def main() -> int:
    args = parse_args()

    if args.backend is not None:
        import matplotlib

        matplotlib.use(args.backend)

    boxes, labels = load_draw_payload(args.json, args.device)
    show_obb_aircraft(boxes, labels)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
